apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-detection
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/Hemanthmahendrakar/Fraud-Detection-Mlops-Pipeline.git"
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: fraud-mlops

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
