apiVersion: v1
kind: Service

metadata:
  name: fraud-mlops-service
  namespace: fraud-mlops

spec:

  selector:
    app: fraud-mlops

  ports:

  - protocol: TCP
    port: 5000
    targetPort: 5000

  type: NodePort